### ISSUE TITLE
Registro Orden

### ISSUE THREAD

**Issue by UrielBlanco7** [Franco-Mateo-Gomez/tienda-mercadoliebre#1]
Dentro del formulario estaria bueno y creo que visualmente quedaria mejor hacer que el campo donde se completa la contraseña y su confirmacion estuviera debajo de la casilla que requiere el Email.

El resto de la pagina me encanta visualmente muy bien aplicadas las animaciones y se adapta perfectamente a los demas dispositivos.

**Comment by Franco-Mateo-Gomez** [comment]
Gracias por el comentario! Aplicando cambios.
