### ISSUE TITLE
correcion

### ISSUE THREAD

**Issue by alexito2960** [Franco-Mateo-Gomez/tienda-mercadoliebre#2]
HEADER:

esta bien mayormente organizado te falta el foton de hamburguesas que se vea en dispositivos moviles que solo se vea eso no más y la barra de navegacion todos esos links no tienen que estar solo el logo el menu de hamburgesas y el "compra en cuotas y sin tarjeta de credito", más la barra de busqueda , la imagen esa que se ve en dispositivos moviles no tendria que esta seria más para decktops más que nada seria eso.

![Imagen de WhatsApp 2023-02-13 a las 11 28 24](https://user-images.githubusercontent.com/121914750/218486355-13e258d8-371c-4e95-aa34-02d98f8b4d34.jpg)

FOOTER: 

El color de la tipografia le podes cmabiar el color a uno más oscuro a un gris "#666" proba ese, a todo eso le podes poner en un article para que te queda mas junto y con un margen gris te va a quedar más bonito quizas.

**Comment by Franco-Mateo-Gomez** [comment]
Gracias por el comentario. Aplicando correcciones.
